image: registry.c3.b2c.srv/online/ci:node-v9.0-onbuild

stages:
  - build

build:
  stage: build

  script:
    - npm install --registry=https://rnpm.pf.xiaomi.com
    - npm run build
    - mkdir .target && mv * .target && mv .target target

  only:
    - tags

  artifacts:
    paths:
     - target/*
    untracked: false